rollouts:
  - name: part1
    filePattern: part1/**
    target: generated/part1
    duplicateHandling: 'queue'
    validateScript: |
      set -e
      echo "part1 on ring $ROLLOUT_CURRENT_RING ✅"
    waitDurations:
      - '5m'
      - '10m'
      - '15m'
